name: Ingesti칩n de Datos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ingest_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Configurar credenciales de Kaggle
        run: |
          mkdir -p ~/.kaggle
          printf '{"username": "%s", "key": "%s"}' "${{ secrets.KAGGLE_USERNAME }}" "${{ secrets.KAGGLE_KEY }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Ejecutar script de ingesta
        run: python src/ingestion.py

      - name: Subir archivos generados como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-ingestion
          path: |
            src/static/db/ingestion.db
            src/static/xlsx/ingestion.xlsx
            src/static/auditoria/ingestion.txt

      - name: Configurar Git para commit autom치tico
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit y Push de los cambios
        run: |
          git add src/static/db/ingestion.db src/static/xlsx/ingestion.xlsx src/static/auditoria/ingestion.txt
          git commit -m "Actualizaci칩n autom치tica de evidencias de ingesta" || echo "No hay cambios para commitear"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}